DROP TABLE IF EXISTS activities;
DROP TABLE IF EXISTS accounts;

CREATE TABLE accounts (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(250) NOT NULL,
	last_name VARCHAR(250) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL
);

CREATE TABLE activities (
	id SERIAL PRIMARY KEY,
	name VARCHAR(200) UNIQUE NOT NULL,
	description VARCHAR(1000) NOT NULL,
	image_url VARCHAR(300) UNIQUE NOT NULL,
	location VARCHAR(200) NOT NULL,
    link_url VARCHAR(300) NOT NULL,
    created_at DATE NOT NULL
);